services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webz_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=webz_data
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - WEBZ_API_TOKEN=20756445-dcfa-42f8-a9e5-5a28e06eaffb
      - WEBZ_API_BASE_URL=https://api.webz.io
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: