services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - DB_HOST:${DB_HOST}
      - DB_PORT:${DB_PORT}
      - DB_NAME:{DB_NAME}
      - DB_USER:{DB_USER}
      - DB_PASSWORD:${DB_PASSWORD}
      - WEBZ_API_TOKEN:${WEBZ_API_TOKEN}
      - WEBZ_API_BASE_URL:${WEBZ_API_BASE_URL}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
